### ISSUE TITLE
1.6pre7 in Firefox26  "Foreign links" open in background function is invalid

### ISSUE THREAD

**Issue by kpdd** [ithinc/tabutils#1]
Uncheck "Foreign links/Focus new tab from", click Word or QQ link is always open in new tab , I try link TMP not, so very vexed. Please repair, thanks.
AMO is not through this version, can not install with AMO.

**Comment by MalcKear** [comment]
tab utilities 1.6pre7 - http://pan.baidu.com/s/1dDxJV2p

**Comment by ithinc** [comment]
Introduced by Bug 902695 - https://bugzilla.mozilla.org/show_bug.cgi?id=902695.
Uncheck the "Focus new tabs from / Diverted windows" option instead for now.

**Comment by kpdd** [comment]
Thanks, AMO thought this version now. 
I do not like "Diverted windows", a troubling.
Just Waiting Mozilla, I had to use Tab Mix Plus sometimes.

**Comment by kpdd** [comment]
yeah, i try 1.6pre8 fixed.
good job, thanks.
