### ISSUE TITLE
FF26 TU1.6pre7 bug

### ISSUE THREAD

**Issue by RedHorizon** [ithinc/tabutils#11]
Create a new FF profile, launch FF
Install TU1.6pre7, browser will restart
Open Panorama window by pressing Ctrl-Shift-E, create a new group by clicking left mouse button and moving your mouse
Name this new group somehow - "ABC", for example
Return to the previous panorama group, click the tab - Move to group - you'll see that group "ABC" has a "null" title.

**Comment by ithinc** [comment]
The "null" is not the title of the group. The group title is at the end like "ABC[0]". The menuitem label is the label of the active tab of the group. I'll remove the "null" stuff though.
