### ISSUE TITLE
"Ctrl+Tab to navigate tabs in MRU order across sessions" is not working with Firefox 32.0.1

### ISSUE THREAD

**Issue by gberche-orange** [ithinc/tabutils#118]
With FF 32.0 CTRL+TAB seems to alwas navigate to tab on the left, ignoring the MRU option preference. CTR+TAB in MRU order is by far the feature I most rely on in tab utilities.

Same feedback independently posted onto https://addons.mozilla.org/fr/firefox/addon/tab-utilities/reviews/627080/

**Comment by RedHorizon** [comment]
I confirm this bug on FF32.0.3, TU1.28.1
However, Firefox has this functionality in stock: disable MRU option in TU, type about:config in the adress bar, set browser.ctrlTab.previews to true.

**Comment by gberche-orange** [comment]
Thanks @RedHorizon closing the issue as the builtin FF functionality seems indeed working fine (across tab groups) and provides a preview of the tab. A bit slower maybe than tabutilities, I'll test it with a large number of open tabs in FF.
