### ISSUE TITLE
New private window not working when "Enable single windows mode" is checked

### ISSUE THREAD

**Issue by dhellwich** [ithinc/tabutils#12]
Subject says it all:

A new private window is not working when "Enable single windows mode" is checked in TU. It's opening a new (non private) tab in the current window, instead of opening a private window in a new window.

/EDIT
I'm using latest FF26 and TU 1.6pre7

**Comment by ithinc** [comment]
It is supposed to behave so.

**Comment by dhellwich** [comment]
Thanks for the reply. In previous versions it behaved as I described (it opened a new private window, although "enable single window mode" was checked).

If this is the new behaviour, then I guess it's ok. Thanks.
