### ISSUE TITLE
Close tabs bug FF26 TU1.6pre9 and TU1.5.26

### ISSUE THREAD

**Issue by RedHorizon** [ithinc/tabutils#14]
FF26, TU1.5.26/1.6pre9, new profile (stacks are disabled by default so it looks like they are not the reason). However, bug is reproduced with stacks enabled too. Wait until all the tabs that you open finish loading.

1.Create new profile, launch FF, there will be one tab - open any web-page in it
2.Open any link on this web-page using ctrl-lmb
3.Open a new tab using new tab button on the tab bar
4.Switch to the second tab from the left, close it with Ctrl-W
5.Switch to the second tab (the one you opened in step 3), open any web-page in it, open any link on the web-page by ctrl-lmb
6.Close this tab using Ctrl-W, focus will move to the tab you've just opened - close it with Ctrl-W as well
7.You now have one tab - open any link from it using Ctrl-lmb.
8.Open a new tab using new tab button on the tab bar, load any web-page in it
9.Open 5 links on this web-page using Ctrl-lmb
10.Close the tab that currently has focus (parent tab)
11.Open a new tab using new tab button on the tab bar, load any web-page in it
12.Open any link on the web-page by ctrl-lmb
13.Close tab that currently has focus
14.Close the tab that received focus
For some reason the focus will now move to the first tab though it was supposed to move to the last tab.

I think this is not the only way to reproduce this bug

**Comment by RedHorizon** [comment]
I found an easier way to reproduce this bug.
FF27,  TU1.5.27 and TU1.6pre12, new clean profile, default settings.

Create new profile, launch FF, install TU - you will have one or two tabs open
Open new tabs using new tab button on tab bar until you have 8 (this is important!) tabs open
Focus will be on the last tab, open any link in the last tab with ctrl-lmb, switch to the opened tab with Ctrl-Tab
Open a new tab using new tab button on tab bar, open any link in it using Ctrl-lmb, close current tab with Ctrl-W, close tab that received focus with Ctrl-W

Focus will move to the first tab for some reason though it was supposed to move to the last tab.

**Comment by ithinc** [comment]
Introduced by [Bug 586153 – unique panel ID shouldn't use Date.now()](https://bugzilla.mozilla.org/show_bug.cgi?id=586153).
Fixed by 3a283b8616d9a0e2026a43a4e769e32a2da7854e.
