### ISSUE TITLE
Closed tab does not restore in original position

### ISSUE THREAD

**Issue by spvkgn** [ithinc/tabutils#147]
With enabled TU closed tab does not restore in original position. With disabled TU it works as it should be.
`extensions.tabutils.restoreOriginalPosition = true`
FF 34 TU 1.5.28.1
Can anybody confirm this?

**Comment by yfdyh000** [comment]
Confirmed.

```
TypeError: access to strict mode caller function is censored tulib.js line 99 > eval:3
if (arguments.callee.caller.name == "ssi_undoCloseTab" && !TU_getPref("extensions.tabutils.restoreOriginalPosition", true))
```

`arguments.callee.caller.name` is removed in Fx35 and above when strict mode.
TMP have a `isCallerInList` implementation in modules/log.jsm.
https://bitbucket.org/onemen/tabmixplus/src/af23fcc4529a69990c68d54a9861137fe977ba06/modules/log.jsm?at=default#cl-164

**Comment by awalkonthebeach** [comment]
same

**Comment by yfdyh000** [comment]
https://github.com/yfdyh000/tabutils/releases 2015.01.25 fixed this.
