### ISSUE TITLE
Bug with  Tab Utilities 1.6pre11 (Faviconized tabs open all links in new tabs)

### ISSUE THREAD

**Issue by untroll** [ithinc/tabutils#15]
Since the last update, a new tab is created when I click on a link in any of my pinned tabs.When the tab is unpinned, the problem doesn't happen. It's clearly a bug and I read that someone else experienced this bug :

"I have 3 tabs faviconized: My Webmailer. Wikipedia and a third one.
In old version only clicking on an image from commons opens a new tab *), never a new tab from webmailer internal links, in pre11(?) clicking on every WP article opens a new tab and most internal actions in webmailer open new tabs. A lot of tabs while reading e-mails and WP ... Not a good idea ... should be changed ..."

Source : https://addons.mozilla.org/fr/firefox/addon/tab-utilities/ posted by Mueck.

Could you please fix this as soon as possible

Thank you

**Comment by ithinc** [comment]
Set extensions.tabutils.pinTab.autoLock to false in about:config.

**Comment by untroll** [comment]
Thank you

Date: Mon, 3 Feb 2014 17:31:24 -0800
