### ISSUE TITLE
 "Recently Closed Tabs" no longer works

### ISSUE THREAD

**Issue by Rondesgr** [ithinc/tabutils#152]
Until this latest firefox version 35, I could right-click on a tab, select "Recently closed tabs", and then pick a site that I had closed out.

Now, all I see is a small square box in the upper right corner of that option. When I click on "Recently Closed Tabs", nothing happens.

What do I need to do to get "recently closed tabs" to work?

**Comment by yfdyh000** [comment]
https://github.com/yfdyh000/tabutils/releases 2015.01.20 fixed this.

**Comment by Rondesgr** [comment]
WOW!  Thank you for the quick response and for the fix!
