### ISSUE TITLE
"Save Image As..." and "Save Page As..." do not work

### ISSUE THREAD

**Issue by ghost** [ithinc/tabutils#154]
Selecting either from the context menu doesn't appear to do anything.  It does not bring up a dialog prompt to set a filename.  It also does not display an error.  Disabling the tab utils add-on allows both functions to operate normally as intended.

**Comment by yfdyh000** [comment]
https://github.com/yfdyh000/tabutils/releases 2015.03.14
Please report any problems or if it is working properly.

**Comment by ghost** [comment]
That fix works perfectly.  That was very quick.  Awesome sauce!
