### ISSUE TITLE
on mac meta option +3 key won t work for selection pinned tab 3 it does NOTHING

### ISSUE THREAD

**Issue by ale82to** [ithinc/tabutils#17]
on mac meta option +3 key won t work for selection pinned tab 3 it does NOTHING

**Comment by ithinc** [comment]
Anyone else could confirm this?

**Comment by scheinercc** [comment]
------ test env -------
Mac OS X 10.9
Firefox 29.0a2 (Aurora)
TU1.6 pre13

---

works for me.

pressing "cmd/meta + option + 3" opens the 3rd pinned tab (while "cmd/meta + option + 1 / 2 / 4 / 7" open pinned tabs 1, 2, 4, 7 respectively); 
"cmd/meta + option + 5" changes the positioning of the tabs clockwise
"cmd/meta + option + 6" changes the positioning of the tabs counter clockwise
"cmd/meta + option + 8" zooms the whole screen (Mac OS I guess)

**Comment by ithinc** [comment]
Thanks.
