### ISSUE TITLE
the tab hover (view) of the add-on "Tab Scope 1.6.1.1-signed.1-signed" is malfunctioning and is not displayed.

### ISSUE THREAD

**Issue by Shitennouji** [ithinc/tabutils#174]
I use "Pale Moon 27.3.0" and use addons "Tree Style Tab" and "Tab Scope"  together.
After installing the add-on "Tab Utilities Phoenix 2.0.0", the tab hover (view) of the add-on "Tab Scope 1.6.1.1-signed.1-signed" is malfunctioning and is not displayed.

addons "Tree Style Tab 0.0.2" 
oinkin/treestyletab: [Tree Style Tab bare minimum working version for Pale Moon](https://github.com/oinkin/treestyletab)

**Comment by SGvagon** [comment]
Its late I know, but I am using Tab Scope version 1.6.3 and this version (for install this version you must simply edit install file or install addon with Palemoon Tester Tool) works perfectly in Palemoon with Tab Utilities Phoenix.
