### ISSUE TITLE
Move to group missing in menu

### ISSUE THREAD

**Issue by dalek1967** [ithinc/tabutils#19]
I have several profiles that I use so that I can be logged into the same site with different IDs.  I have the same pluggins installed on all of them.  On one profile tho, the option in the menu to "move to group" is missing.  I have cleared all the files, went back to default setting, re-added all the plugins and still get the same result.  Am I doing something wrong or missing something to get this feature in that one profile?  I suspect I have to have a setting wrong somewhere.  I can't find anything in the options menu to make this option available either.  

I wanted to attach a screenshot but it seems that when I click to get a screenshot, the menu goes away too.   Great plugin.  

Thanks.

**Comment by ithinc** [comment]
It's Firefox's behavior.

**Comment by dalek1967** [comment]
Is it a setting that I can change somewhere?  I have tried everything I can think of.  Since this works in most of the profiles, I sort of figured it wasn't the plugin since all use the same version.  I just figured asking the developer may lead to more clues on a fix.  I'm on Firefox 17.0.9 if you have any clues or ideas.  

Thanks much for the plugin.  Great work.

**Comment by ithinc** [comment]
browser.panorama.experienced_first_run

**Comment by dalek1967** [comment]
THANK YOU!!!!!!!!  That worked.
