### ISSUE TITLE
TU1.6pre12/TU1.5.27 new tab in new stack bug

### ISSUE THREAD

**Issue by RedHorizon** [ithinc/tabutils#20]
TU1.6pre12/TU1.5.27, FF27, all FF and TU settings default except for:
extensions.tabutils.autoStack true
extensions.tabutils.dragToStack true
extensions.tabutils.autoCollapseNewStack false

Launch FF - there should be one tab open, open any link in current tab using ctrl-lmb - you'll have a stack
Switch to the opened tab with Ctrl-Tab, then switch back with Ctrl-Tab again
Drag right tab onto the left one - stack will change color
Open any link in current tab with ctrl-lmb - you'll see that new tab was created not after the current one, but after the last one.

**Comment by ithinc** [comment]
Fixed by fe71d59614334d0990a55eee00575d614d3def1c.
