### ISSUE TITLE
[TU1.6pre11+/TU1.5.27 / FF 29.0a2 / mac] on exiting video fullscreen tab and URL bar hidden

### ISSUE THREAD

**Issue by scheinercc** [ithinc/tabutils#21]
tested with:
TU1.6pre11, 1.6pre12 and 1.5.27
Firefox 29.0a2
Mac OS X 10.9

steps to reproduce:
- go to http://www.tagesschau.de/multimedia/video/video1371962.html; 
- click on the full screen button on the bottom right of the video
- exit the full screen

expected result:
after leaving the fullscreen mode the browser window gets restored to the state before entering fullscreen

actual result:
- the OSX controlers are visible: main bar, close/minimize/maximize buttons, fullscreen arrow
- browser chrome hidden: tab bar and URL/search bar are hidden;

see screen: this shows the top-left corner of the browser after exiting fullscreen, with the OSX buttons, the backround image of the page, where the browser chrome should be

![screen shot 2014-02-11 at 19 50 38](https://f.cloud.github.com/assets/817856/2135181/e736b2a4-92f9-11e3-8611-ef0a82c4f2fa.png)

If I have "bookmarks" visible, they are partly visible after leaving fullscreen.

**Comment by ithinc** [comment]
Thanks for the detail report. Could you please have a test with the following about:config pref?

```
pref("extensions.tabutils.js.showXULChrome", 'TU_hookCode("FullScreen.showXULChrome", /.*(var ctlsOnTabbar.*)/, "$1");');
```

**Comment by scheinercc** [comment]
You're brilliant, ithinc. That seems to work just fine, definitely with my test case above.

Just FYI, applied it via "right click" > "New" > "String" in about:config

Let me know if I can help you with any more tests.

Thanks for your quick help & have a great weekend

**Comment by ithinc** [comment]
Please have a test for #17 issue, thanks.
