### ISSUE TITLE
[TU1.6pre12/TU1.5.27 / FF 29.0a2 / mac] tab-groups icon broken

### ISSUE THREAD

**Issue by scheinercc** [ithinc/tabutils#22]
tested with:
TU1.6pre11, 1.6pre12 and 1.5.27
Firefox 29.0a2
Mac OS X 10.9

screen: TU activated - blank space with little arrow instead of tab groups icon 
![screen shot 2014-02-11 at 20 03 03](https://f.cloud.github.com/assets/817856/2135290/9554a732-92fb-11e3-9571-50cc8fab7c1d.png)

screen: TU de-activated - tab groups icon 
![screen shot 2014-02-11 at 20 04 26](https://f.cloud.github.com/assets/817856/2135293/a13b4f10-92fb-11e3-9a98-26444182193b.png)

---

Thanks for all your help!

**Comment by ithinc** [comment]
Set extensions.tabutils.css.fixTabViewButton to "" in about:config and make a restart.

**Comment by scheinercc** [comment]
Thanks! that does the trick :)
