### ISSUE TITLE
Thank You, And A Humble Suggestion

### ISSUE THREAD

**Issue by LouieChuckyMerry** [ithinc/tabutils#23]
ithinc:  Thank you for your excellent add-on, I really appreciate it.  I'd like to humbly suggest that you add the feature "extensions.tabutils.dragToUnStack", the exact opposite of "extensions.tabutils.dragToStack".  I think that this would make your already five-star add-on even better.  Thanks for your consideration, and thanks again for Tab Utilities.

**Comment by ithinc** [comment]
Drag to unstack works by default. You need to drag a tab before or after another non-stacked tab to unstack/move it.

**Comment by LouieChuckyMerry** [comment]
Thanks for that, I feel a bit stupid.  I was only trying to drag a tab out either end of a stack (that would be a nice feature ;-) and never actually dragged it past one tab either side.  Next time I'll try a little harder before I bother you :) .
