### ISSUE TITLE
Incompatibility 

### ISSUE THREAD

**Issue by R-Miller** [ithinc/tabutils#27]
This is sent to inform you of a problem.
There is an incompatibility issue between Tab Utilities (either version1.5.26 and 1.5.27) and Mozilla Firefox version 27, as well as 26.
What takes place is for 3 minutes all is normal tabs on the work tab bar is in hibernation, then they all become active (1st clue), then, if one goes to history then down to the recently closed tabs and recently closed windows lists one see that they are gone, and then one goes to the tabs that are layered they have become single. Thus wiping out a great deal of work. 
Also, after going to site, an example Wikipedia, and look at several pages, after this one goes to the top left to the arrows that move you backward or forward, and you move back to the beginning page (homepage). Then move on to the next tab. Then you close the browser. The next day you open the browser and open Wikipedia again, only it is not the homepage , but the last page you looked at at that site, with no arrows in the top left  is gone, meaning that is the beginning page, not even reloading the tab helps. One has pull up the site once more. This holds true for any site visited.
Thank you,
Mr. R. Miller

**Comment by ithinc** [comment]
Have you tested it in a clean profile with only one extension TU installed?

**Comment by ithinc** [comment]
See #30.
