### ISSUE TITLE
[TU1.6pre14 / FF 29.0a2 / win7/mac] Misc. issues with pinned tabs

### ISSUE THREAD

**Issue by scheinercc** [ithinc/tabutils#28]
There are several issues with pinned tabs atm.

**tested with**
TU1.6pre14
Firefox 29.0a2 (built 2014-02-19)
Windows 7 SP1 / Mac OS 10.9

**expected**
- pinned tabs can be moved
- pinned tabs can be removed
- there is an animation when moving a pinned tab (see #24 )
- there are delimiters between pinned tabs

_screen cast TU disabled_
http://ubuntuone.com/1mjFi9N6YS7ycASCLAXFQl

**actual**
- no delimiters between pinned tabs
- no animation when moving a pinned tab, but a little arrow symbol instead
- when trying to move a pinned tab, a second pinned "ghost" tab gets create which 'on click' opens a new normal tab
- changing the pinned tabs ( while TU is disabled or enabled ) **will bring back the old (outdated) pinned tabs and tab sequence** (when I enable TU again) after a browser restart

_screen cast TU enabled_
http://ubuntuone.com/2TVe9bNJZhHmuw6XKbuxZ9

It seems that TU completely locked down my pinned tabs to some saved state and doesn't let me update them. I can't say since when this is happening, though.

Let me know if you need more infos / test case / etc.

**Comment by ithinc** [comment]
Set extensions.tabutils.pinTab.showPhantom to false.
Set extensions.tabutils.disableTabMoveAnimation to false.
Set extensions.tabutils.css.disableTabMoveAnimation to "" and restart Fx.

Delimiters will be addressed later.

TU provided pin tab feature before Fx4 and has a local implemention.
Australis theme messes up Phantom tabs, which will be addressed later.

**Comment by scheinercc** [comment]
Great, thanks!

Will give it a go tomorrow and let you know how it goes.

**Comment by ithinc** [comment]
Import the following setting to show pinned tab separator.

```
pref("extensions.tabutils.css.pinnedTabSeparator", ".tabbrowser-tab[pinned]::before {height: 100%;position: absolute;}");
```

**Comment by scheinercc** [comment]
yeap, that does the trick ;) thank you
_updated title and first comment; added 'Mac' as platform_
