### ISSUE TITLE
Add extensions.tabutils.menu.context_copyTabURL to the options window

### ISSUE THREAD

**Issue by anewuser** [ithinc/tabutils#29]
Hello. Please add **extensions.tabutils.menu.context_copyTabURL** to **Appearance -> Menus -> Tab Context Menu**. It's a useful option that shouldn't be hidden from users.

**Comment by ithinc** [comment]
That is an example to show how to add a custom menuitem via about:config.

**Comment by ithinc** [comment]
Fixed by 2eec70b0609d9a63377346473236f5c671cb5d43.

**Comment by anewuser** [comment]
Thank you! :+1:
