### ISSUE TITLE
【BUG报告】新建一个标签页，会自动缩短标签长度并且右侧留白。

### ISSUE THREAD

**Issue by ruleroller** [ithinc/tabutils#3]
勾选“多行标签栏”，如果没有满一行，标签一多，当前激活标签在最后一个的时候，此时新建一个标签页，会自动缩短标签长度，标签栏右侧突然空出的情况。

不知道这里怎么传截图，在mozest有bug的截图：

https://g.mozest.com/viewthread.php?tid=33102&page=162#pid311647

1.6p7 ，Firefox 26.0

**Comment by ithinc** [comment]
请用空白配置文件测试。

**Comment by ruleroller** [comment]
谢回复，我刚用空白配置文件测试了，的确没有重现。

但是，当我“定制”了下布局，将新建标签页右侧的“+”按钮拖动到别处，那个bug状况就重现了。我也不知道这算不算bug啦，目前已经乖乖地将此按钮还原到默认的位置了。:)

**Comment by ithinc** [comment]
已确认。这个问题我以前调查过，问题出在Firefox的代码中，暂时无解。保留"+"按钮吧。
