### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by R-Miller** [ithinc/tabutils#30]
I gave the  following post: 
On Wed, Feb 19, 2014 at 1:07 PM, R-Miller notifications@github.com wrote:

> This is sent to inform you of a problem.
> There is an incompatibility issue between Tab Utilities (either
> version1.5.26 and 1.5.27) and Mozilla Firefox version 27, as well as 26.
> What takes place is for 3 minutes all is normal tabs on the work tab bar
> is in hibernation, then they all become active (1st clue), then, if one
> goes to history then down to the recently closed tabs and recently closed
> windows lists one see that they are gone, and then one goes to the tabs
> that are layered they have become single. Thus wiping out a great deal of
> work.
> Also, after going to site, an example Wikipedia, and looking at several
> pages, after this one goes to the top left to the arrows that move you
> backward or forward, and you move back to the beginning page (homepage).
> Then move on to the next tab. Then you close the browser. The next day you
> open the browser and open Wikipedia again, only it is not the homepage ,
> but the last page you looked at at that site, with no arrows in the top
> left is gone, meaning that is the beginning page, not even reloading the
> tab helps. One has to pull up the site once more. This holds true for any site
> visited.
> Thank you,
> Mr. R. Miller
> You responded to my post with the following question:
> Have you tested it in a clean profile with only one extension TU installed? 

My answer is yes . I had removed all traces of any past programs, when I noticed the problems (below), and then reinstalled your program (either 1.5.26, or 1.5.27)
"After going to site, an example Wikipedia, and looking at several pages, after this one goes to the top left to the arrows that move you backward or forward, and you move back to the beginning page (homepage). Then move on to the next tab. Then you close the browser. The next day you open the browser and open Wikipedia again, only it is not the homepage, but the last page you looked at at that site, with no arrows in the top left is gone, meaning that is the beginning page, not even reloading the tab helps. One has to pull up the site once more."
The above described problem persisted after these actions.
As far as the incompatibility, I had run 1.5. 27 for a time, after I had did the actions described above, then the Mozilla Firefox update notice appeared and I updated. Then the incompatibility issue I described (see above) took place.
I informed you of this issue not to complain, for I do love your program (it is very helpful for researchers), but to inform so that you would know that there is a problem: so you could work on it.

**Comment by ithinc** [comment]
Thanks for your long post, but I get little info from it. Please refer to scheinercc's reports (#21 for example) to make a clear report. Create a new profile, then record what you do, what you see and what you expect, step by step.

**Comment by R-Miller** [comment]
You state that you got little info from my last post. I do not know how to be more clear, or informative, without you using your yes to see what I am saying, or being here and seeing the screen. I did check out what you asked me to.
In my posts, I had stated the versions of Tab Utilities (1.5.26 and 1.5.27) that I used. Also, the version of Mozilla Firefox 27. 
I used Tab Utilities 1.5.26 with Mozilla Firefox 26, with the problem of all tabs on the work tab bar going from hibernation to active, all layered tabs became single tabs, and recently closed tabs and recently closed windows disappearing. Also, I used the Tab Utilities1.5.26 with  Mozilla Firefox 27 with the same results.
I used Tab Utilities 1.5.27 with Mozilla Firefox 26, with the problem of all 
tabs on the work tab bar going from hibernation to active, all layered 
tabs became single tabs, and recently closed tabs and recently closed 
windows disappearing. Also, I used the Tab Utilities version 1.5.27 
with  Mozilla Firefox 27 with the same results.
With each I had uninstalled and removed all traces of the Tab Utilities version 1.5.26 before installing the version 1.5.27.
[1] I had gone back to an older version of Mozilla Firefox 19 and first I tried Tab Utilities1.5.26, then I had uninstalled and removed all traces of the Tab Utilities version 1.5.26 before installing the version 1.5.27, and using it with Mozilla Firefox 19. With both the same result, I would pull up a site, like yahoo search (1), I would precede to type in the search window a title and got search results. I would repeat the procedure. I may have looked at 6 or 7 different titles before I went to the top left corner to the arrows that moves backwards, or forwards, and used them to move me back to beginning page that I started on, then moved to another work tab (2). I read this tab. I then closed the browser. 
When I opened the browser again, the last tab (2) that I worked on was open , as it should have been. I opened the hibernating work tab (1), but instead of it being at the beginning page it was on another page (like 5 or 6 of the search described above), and I could not get back to the beginning page (homepage)(no arrows in the top left hand corner) without pulling up the site once more.
I recently tried an experiment, for a few days, where I tried Mozilla Firefox 19 with an older version of Tab Utilities. The results none of the problems described above [1].
Here I have once more described in detail the problems and the versions of Tab Utilities and versions of Mozilla Firefox. If you can not follow, or understand, what I am saying, then learn English, or start listening.
Mr. R. Miller

On Thursday, February 20, 2014 8:41 PM, ithinc notifications@github.com wrote:

Thanks for your long post, but I get little info from it. Please refer to scheinercc's reports (#21 for example) to make a clear report. Create a new profile, then record what you do, what you see and what you expect.

**Comment by ithinc** [comment]
I suggest you:
1/ Create a new profile with Fx27, and install TU 1.5.27. 
Don't touch any settings, if you change any setting, write it down here.
2/ Reproduce your problem with the least steps and write it down here. 
Write down what you do, what you see and what you expect, step by step. 
Don't write a long paragraph. Number your steps. Each step contains only one action. 
Thanks.

**Comment by ithinc** [comment]
See #6.

**Comment by R-Miller** [comment]
I am sorry to use this method, but the address that I typed in for you was rejected.
I have some questions about your Tab Utility program.

Under Tabs: Tabs Opening: (open with new tab for) what takes
place if the search bar box is checked? Under Appearance: Menus: Tab Context Menu: What takes place
if the lock tab box is hit? Does it prevent tabs from being closed by accident
(such as a browser crash)?
Is there a link where one can get definitions of various functions and instructions on your program? 

On Wednesday, February 26, 2014 3:12 PM, ralph miller mi1951@yahoo.com wrote:

On , ralph miller mi1951@yahoo.com wrote:

You state that you got little info from my last post. I do not know how to be more clear, or informative, without you using your yes to see what I am saying, or being here and seeing the screen. I did check out what you asked me to.
In my posts, I had stated the versions of Tab Utilities (1.5.26 and 1.5.27) that I used. Also, the version of Mozilla Firefox 27. 
I used Tab Utilities 1.5.26 with Mozilla Firefox 26, with the problem of all tabs on the work tab bar going from hibernation to active, all layered tabs became single tabs, and recently closed tabs and recently closed windows disappearing. Also, I used the Tab Utilities1.5.26 with  Mozilla Firefox 27 with the same results.
I used Tab Utilities 1.5.27 with Mozilla Firefox 26, with the problem of all 
tabs on the work tab bar going from hibernation to active, all layered 
tabs became single tabs, and recently closed tabs and recently closed 
windows disappearing. Also, I used the Tab Utilities version 1.5.27 
with  Mozilla Firefox 27 with the same results.
With each I had uninstalled and removed all traces of the Tab Utilities version 1.5.26 before installing the version 1.5.27.
[1] I had gone back to an older version of Mozilla Firefox 19 and first I tried Tab Utilities1.5.26, then I had uninstalled and removed all traces of the Tab Utilities version 1.5.26 before installing the version 1.5.27, and using it with Mozilla Firefox 19. With both the same result, I would pull up a site, like yahoo search (1), I would precede to type in the search window a title and got search results. I would repeat the procedure. I may have looked at 6 or 7 different titles before I went to the top left corner to the arrows that moves backwards, or forwards, and used them to move me back to beginning page that I started on, then moved to another work tab (2). I read this tab. I then closed the browser. 
When I opened the
 browser again, the last tab (2) that I
 worked on was open , as it should have been. I opened the hibernating work tab (1), but instead of it being at the beginning page it was on another page (like 5 or 6 of the search described above), and I could not get back to the beginning page (homepage)(no arrows in the top left hand corner) without pulling up the site once more.
I recently tried an experiment, for a few days, where I tried Mozilla Firefox 19 with an older version of Tab Utilities. The results none of the problems described above [1].
Here I have once more described in detail the problems and the versions of Tab Utilities and versions of Mozilla Firefox. If you can not follow, or understand, what I am saying, then learn English, or start listening.
Mr. R. Miller

On Thursday, February 20, 2014 8:41 PM, ithinc notifications@github.com wrote:

Thanks for your long post, but I get little info from it. Please refer to scheinercc's reports (#21 for example) to make a clear report. Create a new profile, then record what you do, what you see and what you expect.
