### ISSUE TITLE
Disable Tab Stacking

### ISSUE THREAD

**Issue by tsaloo** [ithinc/tabutils#31]
Hi. I was wondering how can I disable auto tab stacking. I can't find this option in settings. Thanks.

**Comment by ithinc** [comment]
Set extensions.tabutils.autoStack to false in about:config.

**Comment by tsaloo** [comment]
Thank you for the quick reply! Thank you for the awesome add on too! I can't live without it.

**Comment by ithinc** [comment]
[Tab Stacking options](https://github.com/ithinc/tabutils/wiki/Tab-Stacking-options)
