### ISSUE TITLE
Firefox Aurora 29.0a2 australis TU1.6.pre17 Ctrl+left click on Tab or any other combination doesnt close group/stack

### ISSUE THREAD

**Issue by loa11** [ithinc/tabutils#33]
Firefox Aurora 29.0a2, australis,  TU1.6.pre17,
 Ctrl+left click on a Tab or any other combination like alt+left click doesn't close the group/stack.

**Comment by loa11** [comment]
Just to poke your memory 

pref("extensions.tabutils.mouse.100.label", "Close Stack");
pref("extensions.tabutils.mouse.100.oncommand", "document.getElementById('context_closeGroup').doCommand();");
pref("extensions.tabutils.ctrlClickTab", 100);

Seems you dropped support for custom mouse click features

**Comment by loa11** [comment]
[URL=http://www.imagebam.com/image/b44c2c311915801][IMG]http://thumbnails112.imagebam.com/31192/b44c2c311915801.jpg[/IMG][/URL]

**Comment by ithinc** [comment]
Wow, really huge! There is some change recently. You need to change "context_closeGroup" to "context_closeStack".

**Comment by loa11** [comment]
Thanks few minutes ago I started looking into the source code but you made post before I stumble upon changes.
Thanks for the reply.
