### ISSUE TITLE
FF27+ XUL Overlay issue

### ISSUE THREAD

**Issue by sparhami** [ithinc/tabutils#34]
In tabutils.xul, there is an overlay being done that assumes #browser is a child of #browser-panel. In Firefox 27, #browser is now a child of #content-deck which is in turn a child of #browser-panel.

This causes a #browser element to be created in the wrong place with the toggler elements inside of it rather than in the real #browser element.

**Comment by ithinc** [comment]
Thanks for your remind. I suppose the issue should be in Fx29+.
