### ISSUE TITLE
Ctrl+Tab regression

### ISSUE THREAD

**Issue by pintassilgo** [ithinc/tabutils#35]
I use Ctrl + Tab to navigate tabs in the tab bar order.

The tab switch occurs on key down Ctrl + Tab, without waiting releasing Ctrl key.

But in two most recent versions (1.6pre17 and 1.6pre18), the tab switch only occurs when I release Ctrl key.

This issue only occurs with Tab Utils 1.6pre17/18 + Tile Tabs, don't ask me why. For months these two extensions lived great together. After several tests changing to earlier versions, I concluded that this issue is caused by the new version of Tab Utils (1.6pre17, not solved in 1.6pre18).

One detail is that chrome tabs (like about:config, about:addons) switch without waiting Ctrl release. Only page tabs (like Google, GitHub) are affected by this issue.

**Comment by ithinc** [comment]
Set extensions.tabutils.handleCtrl to false in about:config. 
Introduced by f8f9a26f722f5cb7b7d9442d47e0675452b3602d. It's now designed so.
And your last statement seems invalid.

**Comment by pintassilgo** [comment]
Solved, thanks.

But my last statement is valid, I can switch between chrome tabs while keeping Ctrl pressed (Ctrl+Tab, Tab, Tab, Tab, Tab) even with extensions.tabutils.handleCtrl=true. In this case, normal tabs switch only the active tab in tab-bar and the address in nav-bar, but not the page content.

**Comment by ithinc** [comment]
That's because some tabs are loaded, some are unloaded. You see the page content because it has been loaded.
