### ISSUE TITLE
Auto-close unintentional tabs cancels downloads in new windows

### ISSUE THREAD

**Issue by AlexVallat** [ithinc/tabutils#36]
For example, if you shift-click a download link to open it in a new window, or if you click an external link and it opens a new firefox window to download it, then the auto-close feature will close that window and cancel the download. If you choose to Save As, then it will do so while the Save As dialog is shown, immediately closing it too.

Ideally, I'd still like it to be able to auto-close the new blank window, but if it can't be made to do so without cancelling the download then it would be less harmful to just leave it open.

**Comment by ithinc** [comment]
Confirmed. Thanks for your report. I'll investigate it sometime later.

**Comment by ithinc** [comment]
This is a latent bug since Fx3.6 era.
