### ISSUE TITLE
自动关闭非主动打开的空白标签页,造成无法下载文本链接

### ISSUE THREAD

**Issue by Cye3s** [ithinc/tabutils#38]
Fx 28+全新安装pre19
选中"自动关闭非主动打开的空白标签页"
选中以下文本

```
http://luci.subsignal.org/~jow/reghack/reghack.mips.elf 
```

右键, 在新标签页中打开, 跳出保存窗口, 但点击确定后不能开始下载

如果不选择"自动关闭非主动打开的空白标签页", 则无此问题

**Comment by ithinc** [comment]
这个功能曾经好用过吗？还是在某个Fx版本之后才失效的？

**Comment by ithinc** [comment]
Last good nightly: 2012-10-22
First bad nightly: 2012-10-23

Pushlog:
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=1c3e4cb1f754&tochange=48502b61a63e

**Comment by ithinc** [comment]
Introduced by [Bug 722995 – DownloadLastDir.jsm uses global Private Browsing state to make decisions](https://bugzilla.mozilla.org/show_bug.cgi?id=722995).

**Comment by Cye3s** [comment]
这个没注意，Firefox版本更新太快，TU又有段时间没更新，我记得应该是从19.0后开始出现
之前都好用

**Comment by ithinc** [comment]
不打开Save As对话框，保存到默认位置是没问题的。

**Comment by ithinc** [comment]
Test cases:
1/ Open
2/ Save
3/ Save As (Save, Cancel)
4/ Cancel
