### ISSUE TITLE
nightly新主题安装扩展后，工具栏右键菜单多出两个标签栏选项

### ISSUE THREAD

**Issue by hbhghong** [ithinc/tabutils#39]
nightly新主题版默认配置在安装了Tab Utilities后，在工具栏右键点击，弹出的菜单会出现两个标签栏选项。未安装扩展前无标签栏选项

**Comment by ithinc** [comment]
Last good nightly: 2013-12-02
First bad nightly: 2013-12-03

Pushlog:
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=84a5a5800bd3&tochange=8648aa476eef

**Comment by ithinc** [comment]
Introduced by [Bug 943770 – Toolbars with toolboxid attribute set should be included in View --> Toolbars menu](https://bugzilla.mozilla.org/show_bug.cgi?id=943770).
