### ISSUE TITLE
初次打开firefox标签页，恢复按钮是歪的，并且显示有可恢复标签

### ISSUE THREAD

**Issue by ljpiaoxue** [ithinc/tabutils#4]
初次打开firefox标签页，恢复按钮是歪的，并且显示有可恢复标签，实际是没有可恢复的标签页

**Comment by ithinc** [comment]
步骤？

**Comment by ljpiaoxue** [comment]
桌面双击“火狐”图标，打开火狐浏览器，恢复标签页按钮就是亮的，理论上应该是灰色才对，没有可恢复标签页。
鼠标移动到恢复标签页按钮上面，显示按钮背景歪的。

**Comment by ljpiaoxue** [comment]
https://g.mozest.com/thread-33102-163-1

**Comment by ithinc** [comment]
STR: Open a 2nd window.
