### ISSUE TITLE
Tab switching 'broke' in pre18?

### ISSUE THREAD

**Issue by Dognito** [ithinc/tabutils#41]
Open new tabs - A, B, C - from current tab. Before pre18, CTRL+TAB would take me to new tab 'A'. Now I am taken to tab 'C'.

Is there a setting I can change to take me back to the 'old' behaviour? If not, can we have that feature?

Thanks.

**Comment by ithinc** [comment]
This is an intentional change. The old behavior is against MRU order. No setting.

**Comment by Dognito** [comment]
Any chance you could offer a switch for the 'old' behaviour? It just makes more sense to me that CTRL+TAB takes me to the first tab opened, not the last.

**Comment by ithinc** [comment]
Even if we could arrange the tab MRU order arbitrarily in the current session, it will have to be re-ordered by the last access timestamp after a restart. So wontfix it.

**Comment by ithinc** [comment]
See 6eb7645b598085b11e752df5ca242c4c9a6fc75d.

**Comment by ithinc** [comment]
Add the following preference in about:config would implement what you want in the current session.

``` JavaScript
pref("extensions.tabutils.js.onTabOpen", 'TU_hookCode("gBrowser.onTabOpen", /.*splice.*/, function(s) s.replace("1", \'(function() {let index = 1;while (index < tabHistory.length && tabHistory[index].getAttribute("opener") == aTab.getAttribute("opener")) index++;return index;})()\'));');
```

**Comment by Dognito** [comment]
I tried that pref but it didn't work for me. However, I can live with the default behavior.

Thanks for your help.

**Comment by ithinc** [comment]
Save it as a text file, and import it via "TU Options > Settings > Import...", and Restart Firefox.

**Comment by Dognito** [comment]
Got it. Works perfectly. Thanks again.
