### ISSUE TITLE
ctrl左键链接在当前页打开无效

### ISSUE THREAD

**Issue by kidzgy** [ithinc/tabutils#42]
设置:ctrl左键链接为当前标签页打开.
shift 有效,倒是ctrl无效.

而且为什么alt 左键 没有书签和标签的功能?

**Comment by ithinc** [comment]
![untitled0317](https://f.cloud.github.com/assets/1007204/2434885/c369406c-adbb-11e3-91c7-860b0402297c.png)

左键在新标签页打开所有链接时，Ctrl+左键才会在当前标签页打开。Alt键有其他功能。

**Comment by kidzgy** [comment]
那为什么不改为ctrl跟shift一样的呢?本来老习惯是,默认的是shift打开新标签或新窗口.
不管如何,不管有没有开启新标签页打开所有链接,摁住ctrl的话都是当前打开这样不好吗?
而且摁ctrl时肯定都是人为有意的

**Comment by ithinc** [comment]
Ctrl+左键条件性的实现可以保证左键/Ctrl+左键永远是一个当前页，一个新标签页。
你可以提需求，实不实现另外再说。

**Comment by kidzgy** [comment]
ctrl + 左键点击链接,即便设置为在当前页打开,一直会被强制新标签页打开.
