### ISSUE TITLE
自动关闭非主动打开空白标签页的问题

### ISSUE THREAD

**Issue by kidzgy** [ithinc/tabutils#43]
如果你左键点击某个下载链接,弹出保存对话框,点击保存,这时会添加下载任务.
但是,如果你用拖拉的形式,使之后台打开这个下载链接,也同样会弹出保存框,但你在选择好保存位置点击保存的时候,不会添加下载任务,即没有反应.

**Comment by ithinc** [comment]
请补充平台、版本信息、测试链接。

**Comment by kidzgy** [comment]
http://www.downg.com/soft/32793.html
win7 x64 ff27.0.1

对最下方的"江苏电信下载"拖拉至标签后台,会弹出保存对话框,选择某个文件夹,点击保存,保存对话框消失,这时理应顺利添加下载任务,但是不行.
正常的点击是可以自动关闭空白页的.若取消掉该功能,后台拖动能正常添加.

**Comment by ithinc** [comment]
测试没问题。

**Comment by kidzgy** [comment]
如果能正常保存,那是否会自动关闭空白标签呢?
我是将下载链接拖至后台新标签的,刚才又试了下,是能保存,但是又不能自动关闭空白标签即便我已经设置了.
最最之前的问题是,我使用了其他UC脚本,才使得拖拉后台新标签不能正常保存.对此感到抱歉

**Comment by ithinc** [comment]
新建配置文件测试。

**Comment by kidzgy** [comment]
已查找出原因.
选项-应用程序. 如果我把RAR文件设置为"保存文件"而不是"总是询问".即,我在点击下载链接的时候,不会弹出打开或保存那样的对话框,而是,直接选择保存目录.那么,在拖拉至后台新标签时,大约在0.X秒之后所产生的下载空白标签页会自动关闭,这时你再按保存,便无法正常添加任务.

但是,如果我设置为自动询问,那么在有打开或保存的对话框时我依然选择保存,选择保存目录的时候,后台产生的标签页不会关闭,在选择好后按确定,添加了下载任务了才关闭.

**Comment by ithinc** [comment]
已确认，但这和拖拉没关系。
