### ISSUE TITLE
Faviconized tab width

### ISSUE THREAD

**Issue by pintassilgo** [ithinc/tabutils#45]
I expected faviconized tabs were visually identical to pinned tabs, but faviconized ones are wider.

Here's a screenshot with one pinned tab (left) and one faviconized (right):
http://i.imgur.com/pBZerKY.png

It is possible to change this by reducing faviconized tab widht?

**Comment by ithinc** [comment]
Test with a clean profile.

**Comment by pintassilgo** [comment]
Oh yes, sorry.

A few months ago I installed a userstyle to slim down pinned tabs and forgot it.

To slim down faviconized tabs too:

.tabbrowser-tab[faviconized] .tab-icon-image {
      -moz-margin-start: 3px !important;
      -moz-margin-end: 3px !important;
}
