### ISSUE TITLE
Feature request: Sort tab group list in alphabetical order

### ISSUE THREAD

**Issue by cheyilin** [ithinc/tabutils#46]
![unsorted_tab_group_list](https://f.cloud.github.com/assets/2572321/2445514/c9ebb852-ae74-11e3-9a16-32c8de783c0e.png)

Hi,

The default order is 'group create time' (I guess).
Could you please add this feature?

**Comment by ithinc** [comment]
I would say no. What does the order matter?

**Comment by cheyilin** [comment]
Find/Switch groups more easily I think.
Like [TabGroups Menu](https://addons.mozilla.org/zh-tw/firefox/addon/tabgroups-menu/) addon does:
![51914](https://f.cloud.github.com/assets/2572321/2446405/0de54b76-ae85-11e3-9b8b-7e0fb6a7170e.png)

I ask because the 'TabGroups Menu' is not compatible with TU.
Could you please consider implementing this in TU?

**Comment by ithinc** [comment]
See workaround at: http://forums.mozillazine.org/viewtopic.php?p=13328879#p13328879.

**Comment by cheyilin** [comment]
OK I got it, thanks.

**Comment by cheyilin** [comment]
Hi ithinc,
I would like to implement this feature and send a pull-request back.
Could you tell me where I can start? (which .js, function or anything)

**Comment by ithinc** [comment]
If you'd like to change the display order only, it's in TabView.populateGroupMenu. But I don't plan to accept such a pull request. The Previous/Next Group shortcut keys won't jump according to your modified display order, which will increase confusing. If you really want this change, you'd better submit a request in Bugzilla@Mozilla instead.
You may implement it in an extensions.tabutils.js.\* preference though. Thus you'll get your feature without bothering other users and without another add-on. I may give you some guide if you need.

**Comment by ithinc** [comment]
The following should work.

``` JavaScript
pref("extensions.tabutils.js.populateGroupMenu", 'TU_hookCode("TabView.populateGroupMenu", "forEach", "sort(function(g1, g2) g1.getTitle().localeCompare(g2.getTitle())).forEach");');
```

**Comment by cheyilin** [comment]
Thanks ithinc, the hook trick works perfectly! (v1.6pre20)

I'd like to ask ...
Is it still a compatibility issue since you removed the 'Previous/Next Group shortcut keys'  in 'v1.6pre18'?
If the answer is NO, I'll try to modify function 'TabView.populateGroupMenu'. Maybe you could accept it as an experimental feature in future pre-version.

Thanks again for your help.

**Comment by ithinc** [comment]
Firefox provides Ctrl+(Shift)+` as Previous/Next Group shortcuts, so yes, it is an issue.

**Comment by cheyilin** [comment]
Got it, thank you for pointing this out!
