### ISSUE TITLE
Open submitted forms and JavaScript links in new tab

### ISSUE THREAD

**Issue by blackwind** [ithinc/tabutils#48]
Using MMouse or Ctrl+LMouse on a form submit button or a JavaScript link (such as "javascript:window.open('http://w<b></b>ww.google.com/');") should open the result in a new tab. There's an add-on for forms called <a href="https://addons.mozilla.org/en-US/firefox/addon/tabsubmit/">TabSubmit</a> that does this (but doesn't always seem to work), and there was once an add-on called <a href="http://pastebin.com/FkH7JFkA">Smart Middle Click</a> that handled JavaScript links (but has since been abandoned and removed from AMO). These add-ons should serve as a good starting point for rolling this functionality into TU, where it rightfully belongs.

**Comment by ithinc** [comment]
Someday maybe, but not in the near future.
