### ISSUE TITLE
Can't reload on second window from 1.6pre13 in developer channel.

### ISSUE THREAD

**Issue by lamrongol** [ithinc/tabutils#52]
I can't reload on second window from 1.6pre13 in developer channel.
it's possible on main window or normal version(1.5.27)

**Comment by Siggi0904** [comment]
can u test latest beta 1.6pre21 ?

**Comment by lamrongol** [comment]
Ah, yes. I also tested 1.6pre21 and found this issue occurs from 1.6pre13 to 1.6pre21(it doesn't occur on 1.6pre12).
In addition, it occurs in the following procedure
1. Open two window and open a page in second window.
2. Exit Firefox from "Exit" menu(not using close button on window)
3. Boot Firefox and reload a tab on second window.

**Comment by ithinc** [comment]
Not reproduced. 
How to reload? Reload button or something else?
And how do you determine it doesn't reload?
And did you test with a clean profile?

**Comment by lamrongol** [comment]
> How to reload? Reload button or something else?

Reload button and F5 don't work, either.

> And how do you determine it doesn't reload?

The favicon doesn't change to reload mark and the page is not refreshed.

> And did you test with a clean profile?

Yes, in the following procedure
1. Make a new profile
2.Set Firefox option [General]-[Startup]-[When Firefox starts] "Show my windows and tabs from last time"
3. Install tab utilities 1.6pre21
4.Open [New tab]-[New window] menu and open any page(e.g. http://www.mozilla.jp/firefox/28.0/firstrun/ )
5.Restart

My environment
Firefox 28.0
Windows 7 Home Premium Service Pack1 64bit
I tried in other computer(WIndows XP) and the issue also occur.

**Comment by ithinc** [comment]
Confirmed. Introduced by fbc081fe3431fc21582ee9181a8c97690a06d891.
