### ISSUE TITLE
[bug] history is removed - on tab load?

### ISSUE THREAD

**Issue by TBeholder** [ithinc/tabutils#53]
Load a session, switch tab - "back" button is even shown until the page loads, but gets disabled upon loading.
Happens after upgrade to 1.5.28 tried 1.6pre21 - the same happens.
After removing it, installing 1.5.27 there's no problem again (loading the same saved session for all versions).

**Comment by ithinc** [comment]
Looks like a duplicate of #52. How to reproduce it?

**Comment by TBeholder** [comment]
Not reload, tab history. 
1) switch from a tab with non-empty history to another;
2) "reload" now-background tab.
3) go back. there's "active "back" button, since the page has history...
4) ...but after the tab is loaded again, "back" button turns disabled.
