### ISSUE TITLE
TU1.5.28: Dragging multiple tabs doesn't work

### ISSUE THREAD

**Issue by RedHorizon** [ithinc/tabutils#59]
FF28, TU1.5.28, Win7 SP1 x64, 
New profile, default settings
Open any 3 tabs on tab bar, select the first two (by clicking with Ctrl-LMB, for example), click on the 1st or 2nd tab with LMB and drag it to the right of the last tab.
Expected behaviour: two selected tabs are moved
Actual behaviour: only tab you clicked on is moved

**Comment by ithinc** [comment]
Confirmed. Introduced by 7043243da9389ddd4f4f01d00a1cb2559b91b0fa.
