### ISSUE TITLE
Conflict with Pale Moon's immediate tab resize?

### ISSUE THREAD

**Issue by Gittyperson** [ithinc/tabutils#62]
Pale Moon's browser.tabs.resize_immediately feature does not seem to work with Tab Utilities. The immediate resize will take place only if the far-right tab is closed. With other tabs, the mouse pointer has to go away first as per default.

**Comment by ithinc** [comment]
Set extensions.tabutils.delayResizing to false in about:config.

**Comment by Gittyperson** [comment]
Thanks a lot, I did a "resize" search there - that's why I didn't find this option.
