### ISSUE TITLE
Tab counter not working correctly

### ISSUE THREAD

**Issue by Keith94** [ithinc/tabutils#83]
The tab counter (enabled via Appearance >> Tab Bar) often stops at numbers like 8, 9 or 13 even if you have many more tabs open than that. 

Sometimes after a Firefox restart the counter is stuck and doesn't change, even after loading the existing tabs or opening new ones.

Reproducible with Tab Utilities 1.5.28.1 & 1.6pre21, Nightly 32.

![tabcounter2](https://cloud.githubusercontent.com/assets/5490615/2952527/70f0987c-da3d-11e3-9b7b-8ef4857fa73e.png)

**Comment by RedHorizon** [comment]
FF32.0.3, TU1.5.28.1 Same problem
Create new FF profile, install TU, enable tab counter, start opening new tabs. Tab counter will go to 7 or 8 and then will get stuck.

**Comment by Keith94** [comment]
The [Tab Counter](https://addons.mozilla.org/firefox/addon/tab-counter/) extension can be used as a workaround.

**Comment by RedHorizon** [comment]
FF33, TU1.5.28.1 bug is reproduced as well. Same reproduce steps:
Create new FF profile, install TU, enable tab counter, start opening new tabs. Tab counter will go to 7 or 8 and then will get stuck.

**Comment by Keith94** [comment]
Dead extension.
